// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  productSpecSidebar: [
    {
      type: 'autogenerated',
      dirName: 'product-spec',
    },
  ],
  systemDesignSidebar: [
    {
      type: 'autogenerated',
      dirName: 'system-design',
    },
  ],
  techSpecsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tech-specs',
    },
  ],
  apiSpecSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api-spec',
    },
  ],
  dataSpecSidebar: [
    {
      type: 'autogenerated',
      dirName: 'data-spec',
    },
  ],
  adrSidebar: [
    {
      type: 'autogenerated',
      dirName: 'adr',
    },
  ],
};

module.exports = sidebars;
