// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  systemDesignSidebar: [
    {
      type: 'autogenerated',
      dirName: 'system-design',
    },
  ],
  techSpecsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tech-specs',
    },
  ],
};

module.exports = sidebars;
